title: riceCK
subtitle: 欢迎来到帅比凯的博客
description: learning target
keywords: null
author: 陈凯
language: zh-Hans
timezone: Asia/Shanghai
url: 'http://yoursite.com'
root: /riceBlog
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: next
deploy:
  type: git
  repo: 'https://github.com/riceCk/riceBlog.git'
  branch: master
  repository: 'git@github.com:riceCk.github.io.git'
menu:
  home: /
  categories: /categories
  archives: /archives
  tags: /tags
social:
  GitHub: 'https://github.com/riceCk'
  Weibo: your-weibo-url
live2d:
  enable: true
  pluginModelPath: assets/
model:
  use: live2d-widget-model-chitose
display:
  position: left
  width: 100
  height: 200
mobile:
  show: true
